"""Add tenant_id

Revision ID: 0722637644cc
Revises: e6fd489239ad
Create Date: 2026-07-21 21:02:43.737312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0722637644cc'
down_revision: Union[str, Sequence[str], None] = 'e6fd489239ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    dialect_name = op.get_bind().dialect.name
    op.add_column('order_runs', sa.Column('tenant_id', sa.String(), nullable=False, server_default='demo'))
    op.create_index(op.f('ix_order_runs_tenant_id'), 'order_runs', ['tenant_id'], unique=False)
    if dialect_name != 'sqlite':
        op.alter_column('order_runs', 'tenant_id', server_default=None)
    op.add_column('supervisor_configs', sa.Column('tenant_id', sa.String(), nullable=False, server_default='demo'))
    op.create_index(op.f('ix_supervisor_configs_tenant_id'), 'supervisor_configs', ['tenant_id'], unique=False)
    if dialect_name != 'sqlite':
        op.alter_column('supervisor_configs', 'tenant_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisor_configs_tenant_id'), table_name='supervisor_configs')
    op.drop_column('supervisor_configs', 'tenant_id')
    op.drop_index(op.f('ix_order_runs_tenant_id'), table_name='order_runs')
    op.drop_column('order_runs', 'tenant_id')
    # ### end Alembic commands ###
