"""Add composite index

Revision ID: c39475382ccd
Revises: 8c0d4c8f0a2b
Create Date: 2026-07-22 11:51:21.819576

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c39475382ccd'
down_revision: Union[str, Sequence[str], None] = '8c0d4c8f0a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_order_runs_tenant_order', 'order_runs', ['tenant_id', 'order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_runs_tenant_order', table_name='order_runs')
    # ### end Alembic commands ###
